//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployee()
        {
            this.tblReports = new HashSet<tblReport>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeSurname { get; set; }
        public System.DateTime DateOfBirthday { get; set; }
        public string JMBG { get; set; }
        public string AccountNumber { get; set; }
        public string EMail { get; set; }
        public string Salary { get; set; }
        public string Position { get; set; }
        public string UsernameLogin { get; set; }
        public string PasswordLogin { get; set; }
        public Nullable<int> SectorName { get; set; }
        public Nullable<int> AccessLevel { get; set; }
    
        public virtual tblAccessLevel tblAccessLevel { get; set; }
        public virtual tblSector tblSector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReport> tblReports { get; set; }

        public string Sector
        {
            get
            {
                return $"{tblSector.SectorName}";
            }
        }
        public string Access
        {
            get
            {
                return $"{tblAccessLevel.AccessLevel}";
            }
        }
    }
}
