//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReport
    {
        public int ReportID { get; set; }
        public System.DateTime CurrentDate { get; set; }
        public string ProjectName { get; set; }
        public string WorkHour { get; set; }
        public int Employee { get; set; }
        public string Position { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }

        
    }
}
