//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwManager
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeSurname { get; set; }
        public System.DateTime DateOfBirthday { get; set; }
        public string JMBG { get; set; }
        public string AccountNumber { get; set; }
        public string EMail { get; set; }
        public string Salary { get; set; }
        public string Position { get; set; }
        public string UsernameLogin { get; set; }
        public string PasswordLogin { get; set; }
        public Nullable<int> SectorName { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public int SectorID { get; set; }
        public string Expr1 { get; set; }
        public int AccessLevelID { get; set; }
        public string Expr2 { get; set; }
    }
}
